apiVersion: v1
kind: Secret
metadata:
  name: ssf-bridge-secrets
  namespace: ssf-bridge
  labels:
    app.kubernetes.io/name: ssf-apm-bridge
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  ADMIN_API_KEY: "change-me-to-a-long-random-value"
  BIGIP_USERNAME: "ssf-bridge-svc"
  BIGIP_PASSWORD: "change-me"
