apiVersion: v1
kind: Service
metadata:
  name: ssf-apm-bridge-service
  namespace: ssf-bridge
  labels:
    app.kubernetes.io/name: ssf-apm-bridge
    app.kubernetes.io/component: bridge
spec:
  type: ClusterIP
  selector:
    app: ssf-apm-bridge
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
