apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-ca-bundle
  namespace: ssf-bridge
  labels:
    app.kubernetes.io/name: ssf-apm-bridge
    app.kubernetes.io/component: ca-trust
# To populate this bundle, replace ca-bundle.crt below with your internal Root CA /
# Intermediate CA certificate PEM block.
# Example:
# data:
#   ca-bundle.crt: |
#     -----BEGIN CERTIFICATE-----
#     MIID...
#     -----END CERTIFICATE-----
data:
  ca-bundle.crt: ""
